services:
  whatsapp-service:
    build: 
      context: .
      dockerfile: ./whatsapp-service/Dockerfile-minimal
    container_name: whatsapp-service-minimal
    ports:
      - "3000:3000"
    environment:
      # Ultra-minimal configuration
      - WHATSAPP_HOOK_URL=http://assistant:5000/webhook
      - SESSION_PATH=/app/session
      - NODE_OPTIONS=--max-old-space-size=128 --expose-gc
    volumes:
      - ./whatsapp-session:/app/session
    restart: unless-stopped
    # Ultra-minimal memory limit
    mem_limit: 200m
    # CPU limit for stability
    cpus: '0.3'

  assistant:
    build: .
    container_name: assistant
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - WAHA_URL=http://whatsapp-service-minimal:3000/api/sendText
      - USE_MEMORY_DB=true
    depends_on:
      - whatsapp-service
    # Optimized memory for assistant
    mem_limit: 400m
    cpus: '0.7'
