
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data

  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3000:3000"           # WAHA's API & admin UI
      - "3001:3001"           # WAHA's WebSocket port (if used)
    environment:
      - WHATSAPP_HOOK_URL=http://assistant:5000/webhook
      - WHATSAPP_HOOK_EVENTS=message
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./waha-data:/app/data
    depends_on:
      - redis

  assistant:
    build: .                  # your Flask Dockerfile
    container_name: assistant
    ports:
      - "5000:5000"           # your Flask endpoints
    env_file: .env
    environment:
      - WAHA_URL=http://waha:3000/api/sendText
      - WAHA_KEEPALIVE_INTERVAL=600  # 10 minutes keep-alive interval
    depends_on:
      - waha
