services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - WHATSAPP_HOOK_URL=http://assistant:5000/webhook
      - WHATSAPP_HOOK_EVENTS=message

    volumes:
      - ./waha-data:/app/data

  assistant:
    build: .
    container_name: assistant
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - WAHA_URL=http://waha:3000/api/sendText
      - WAHA_KEEPALIVE_INTERVAL=600
    depends_on:
      - waha
