services:
  whatsapp-service:
    build: ./whatsapp-service
    container_name: whatsapp-service
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_HOOK_URL=http://assistant:5000/webhook
      - WHATSAPP_HOOK_EVENTS=message
      - SHOW_QR=false
    volumes:
      - ./whatsapp-session:/app/session

  assistant:
    build: .
    container_name: assistant
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - WAHA_URL=http://whatsapp-service:3000/api/sendText
      - WAHA_KEEPALIVE_INTERVAL=600
    depends_on:
      - whatsapp-service
